const dataInputs = [
  {
    id: 1,
    name: "firstname",
    type: "text",
    placeholder: "Firstname",
    errorMessage:
      "Please enter a valid name. Your firstname must contain only letters.",
    label: "Firstame(s)*",
    pattern: "^[a-zA-Z0-9]+$",
  },
  {
    id: 2,
    name: "lastname",
    type: "text",
    placeholder: "Lastname",
    errorMessage:
      "Please enter a valid name.  Your firstname must contain only letters.",
    label: "Lastname(s)*",
    pattern: "^[a-zA-Z]+$",
  },
  {
    id: 3,
    name: "email",
    type: "email",
    placeholder: "Email",
    errorMessage: "Please use a valid email",
    label: "Email*",
  },
  {
    id: 4,
    name: "phone",
    type: "number",
    placeholder: "Phone",
    errorMessage: "Please use a valid phone number",
    label: "Phone*",
  },
  // {
  //   id: 5,
  //   name: "country",
  //   type: "text",
  //   placeholder: "Country",
  //   errorMessage: "Choose your country",
  //   label: "Country*",
  // },
  {
    id: 6,
    name: "location",
    type: "text",
    placeholder: "Location",
    errorMessage: "We need to know your location!",
    label: "Location*",
  },
  {
    id: 7,
    name: "address",
    type: "text",
    placeholder: "Address",
    errorMessage: "We need to know your address!",
    label: "Address*",
  },
  {
    id: 8,
    name: "postalcode",
    type: "number",
    placeholder: "Postal code",
    errorMessage: "Please use a valid postal code",
    label: "Postal Code*",
  },
  {
    id: 9,
    name: "vatnumber",
    type: "number",
    placeholder: "VAT Number",
    errorMessage: "Please use a valid VAT number",
    label: "VAT Number*",
  },
];
export default dataInputs;
